name: "Lint & Test"
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4 # v3.3.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - run: go mod download
      - run: go build -v .

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3.3.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # v3.3.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: check-vuln
        run: make check-vuln

      - name: gosec
        uses: securego/gosec@v2.21.1
        env:
          GO111MODULE: on
        with:
          args: ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3.3.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list of Terraform versions to test against.
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
          - '1.3.*'
          - '1.4.*'
          - '1.5.*'
          - '1.6.*'
          - '1.7.*'
          - '1.8.*'
          - '1.9.*'
    steps:
      - uses: actions/checkout@v4 # v3.3.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Test
        run: make coverage
